### ISSUE TITLE
how can i find the file "train_schema-linking.jsonl" ?

### ISSUE THREAD

**Issue by kingda** [zhshLii/PETSQL#2]

**Comment by kingda** [comment]
train_mask_questions = mask_question_with_schema_linking(self.train_schema_jsonl, mask_tag=self.mask_token, value_tag=self.value_token)
AttributeError: 'EuclideanDistanceQuestionMaskSelector' object has no attribute 'train_schema_jsonl'

**Comment by zhshLii** [comment]
Sorry for the ignorance. Now it is uploaded. BTW, one can also generate it by the data_process.py in which the generating process is the same as test_schema-linking.jsonl.

**Comment by kingda** [comment]
你的信我会尽快查收的，Good luck to you！欢迎查看我的个人微博主页，祝您生活愉快
